### ISSUE TITLE
Kodi 19 não ta funcionando multilinks

### ISSUE THREAD

**Issue by RafaelGodoyEbert** [zoreu/meuaddon#3]
Quando abro uma pasta que tem arquivos com 1 link, ele abre tranquilamente, mas quando tento abrir uma pasta que tem multiplos links em cada item, ele da esse erro. 
![image](https://user-images.githubusercontent.com/78083427/147293703-9ec1d7ab-a87d-4baa-8c64-141550c6e8b4.png)
Alguém sabe resolver?

**Comment by zoreu** [comment]
usa o ultimo addon modelo - https://github.com/zoreu/meuaddon/raw/master/download/plugin.video.live.streamspro.zip
pra multlink coloca $lsname=NOME no final do link
